### ISSUE TITLE
Testing external CSI drivers

### ISSUE THREAD

**Issue by Avatat** [vmware-tanzu/sonobuoy#1164]
Hello, Sonobuoy Team!
I'm looking for a way to test storage services from Kubernetes service providers. Now I use Sonobuoy to test Kubernetes service conformity and it works great, but I need to test provider-specific things, like CSI.
Sonobuoy can do storage-related tests from the E2E suite, but to use it with external CSI from a specific provider, I have to give a CSI driver configuration:
https://kubernetes-csi.github.io/docs/functional-testing.html
https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external

Is it possible to run storage tests with the configuration for an external CSI driver directly from Sonobuoy? How can I pass a driver configuration?

**Comment by vladimirvivien** [comment]
Hi @Avatat thank you for reaching out.
By `... need to test provider-specific things, like CSI`, I take it you mean that you would like to exercise E2E conformance for your favorite external CSI driver?  By default Sonobuoy does not support CSI tests for external drivers with external configurations.  However, you can try to configure Sonobuoy with the following custom steps which "may" allow you to run your CSI tests for an external driver.

Disclaimer: I have never tried to run this test, it may or may not work, but give it a try.

* First, create a CSI driver configuration file for your CSI driver as driver.yaml ( as described [here](https://github.com/kubernetes/kubernetes/tree/master/test/e2e/storage/external))
* Next, generate a `sonobuoy.yaml` file that will be used to configure/deploy Sonobuoy and the e22 test image. Make sure to change the  `--e2e-focus` flag value to match your CSI driver name.  The following will setup the test with focus for the `csi-hostpath` driver: 
  ```
   sonobuoy gen --e2e-focus="External.Storage.*csi-hostpath" --e2e-skip="\[Feature:|\[Disruptive\]" > sonobuoy.yaml
  ```
* Now, edit the generated sonobuoy.yaml
* Copy the content of your `driver.yaml` and paste it in sonobuoy.yaml as a `ConfigMap` as such:
```
---
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: hostpath-config
     namespace: sonobuoy
   data:
     driver.yaml: |
       StorageClass:
         FromName: true
       SnapshotClass:
         FromName: true
       DriverInfo:
         Name: hostpath.csi.k8s.io
         Capabilities:
           persistence: true
```
* Next, in sonobuoy.yaml, locate ConfigMap `metadata.name: sonobuoy-plugins-cm`.  
* Find `data.plugin-0.yaml.spec` and do the following:
  * Add `-storage.testdriver` argument in E2E_EXTRA_ARGS
  * Add volume definition for the configMap as `data.plugin-0.ymal.spec.volumes.configMap.hostpath-config-volume`
  * Add a volume mount in the spec at `data.plugin-0.ymal.spec.volumeMounts.hostpath-config-volume`

See example below:
```
apiVersion: v1
data:
  plugin-0.yaml: |
...
    spec:
      command:
      - /run_e2e.sh
      env:
      - name: E2E_FOCUS
        value: External.Storage.*csi-hostpath
      - name: E2E_SKIP
        value: \[Feature:|\[Disruptive\]
      - name: E2E_PARALLEL
        value: "false"
      - name: E2E_USE_GO_RUNNER
        value: "true"
      - name: E2E_EXTRA_ARGS
        value: --progress-report-url=http://localhost:8099/progress -storage.testdriver=/tmp/csi-cfg/driver.yaml
      image: k8s.gcr.io/conformance:v1.19.0
      imagePullPolicy: Always
      name: e2e
      resources: {}
      volumeMounts:
      - mountPath: /tmp/results
        name: results
      - mountPath: /tmp/csi-cfg
        name: hostpath-config-volume  
    volumes:
      - configMap:
        name: hostpath-config
      name: hostpath-config-volume
```
* Save your sonobuoy.yaml
* Execute it with `kubectl -f sonobuoy.yaml`

**Comment by Avatat** [comment]
@vladimirvivien, thank you for your tips!

I prepared sonobuoy.yaml, ran it, but I've got an error:
```
error running plugin e2e: could not create Job resource for Job plugin e2e: Pod \"sonobuoy-e2e-job-2d035bfa1082453e\" is invalid: spec.containers[0].volumeMounts[1].name: Not found: \"hostpath-config-volume\"
```
I noticed that in original sonobuoy.yaml, in `plugin-0.yaml` section, there is no `volumes` list, and in your docs, to version 1.16.1, you wrote:
```
If you need additional mounts besides the default `results` mount that Sonobuoy
always provides, you can define them in the `extra-volumes` field.
```
So, I've tried to use `extra-volumes` instead of `volumes`, but it didn't work either. As I saw later, you removed `extra-volumes` in this commit: https://github.com/vmware-tanzu/sonobuoy/commit/020a7e4c45ad185ebd26375d50d0c0311820b828#diff-52c8852d3d5c3665c836f25a9b3d1428L72
Have you forgotten about `extra-volumes` feature, and removed it by mistake?

**Comment by vladimirvivien** [comment]
Apologies for the late reply.  As I said in the original response, my proposal was never tried and probably would not work at first try.  The problem is Sonobuoy does not support CSI inherently. So the best thing to do right now is to generate a Kubernetes YAML (from instructions above) and tinker with that to see if you can deploy.  I don't know of any other workaround right now.

**Comment by Avatat** [comment]
No worries :)

The problem mentioned above (`extra-volumes` issue) isn't related to CSI. It's Sonobuoy's issue.
Did you see my question:
```
Have you forgotten about extra-volumes feature, and removed it by mistake?
```
?

**Comment by vladimirvivien** [comment]
@Avatat My apologies I did not address your comment about `extra-volumes`.  Looking at the commit hash, the` extra-volume` was removed by a previous engineer.  I am not sure what was the reasoning for removing it, but it appear that the way plugins worked was changed along the way.  

I think this is worth pursuing with Sonobuoy and will be useful to others.  Let me do some digging around and see what can be done to get CSI run as as Sonobuoy test.

**Comment by Avatat** [comment]
Thank you, @vladimirvivien!
The next step to get CSI tests running on external CSI driver is to solve...
```
    volumes:
      - configMap:
        name: hostpath-config
      name: hostpath-config-volume
```
...problem. If you could dig it and `extra-volumes` case too, I will be more than happy :)

**Comment by Avatat** [comment]
Any updates? :)

**Comment by vladimirvivien** [comment]
@Avatat Sorry, we haven't had time to get to this. I will roll this up for higher priority in the next couple of days.

**Comment by khankth** [comment]
Hi,

We have a similar  scenario, we are running on-prem with a external CSI provider, while investigating for a solution to implement reliability tests I came accross this issue.
It would be greatly appriciated if this can be prioritized.

**Comment by vladimirvivien** [comment]
This is on the roadmap to be looked at.  We have a backlog of issues we're working through.

**Comment by fyangd** [comment]
Bumping this thread again as well, we also would love to run external CSI provider tests using sonobuoy, specifically against vSphere.

**Comment by vladimirvivien** [comment]
On the roadmap to be looked at this quarter!!

**Comment by johnSchnake** [comment]
@Avatat I was just peeking at this and don't recall that field `extra-volumes` ever being removed. The commit you linked did some work to flatten some backend structures, but I don't believe it changed anything like removing fields from the manifest entirely. You can even see numerous example yamls with the `extra-volumes` field still. Is it perhaps just an indentation issue?

For instance, you can see that it is still used here https://github.com/vmware-tanzu/sonobuoy/blob/883fc9060c867dbe7dd8d9d926cae0ea3803f900/pkg/plugin/manifest/testdata/extravolumes.yaml#L18 in our test data.

**Comment by johnSchnake** [comment]
@Avatat I think everything you want Sonobuoy to do is already supported; you can send any amount of extra flags/args to the e2e tests. You'll have to look at the k8s docs to know all the config info/flag names though.

The one place I think you could run into a problem would be if you actually needed to not only provide config flags/args but a config file. I think this is the fact when doing some of the cloud provider settings. By default, Sonobuoy doesn't have a way to upload a configMap into a newly created namespace, but you'd have multiple workarounds for that too: (1) put the configmap into a namespace and launch sonobuoy there or (2) use sonobuoy gen and manually specify the configmap info

**Comment by steven166** [comment]
I got this setup working. The thing is that the `volumes` section should be in the `podSpec` block. 
So the yaml should look like this:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-plugins-cm
  namespace: sonobuoy
data:
  plugin-0.yaml: |
    podSpec:
      ...
      volumes:
      - name: hostpath-config-volume
        configMap:
          name: hostpath-config
    spec:
      ...
      env:
      ...
      - name: E2E_EXTRA_ARGS
        value: --progress-report-url=http://localhost:8099/progress -storage.testdriver=/tmp/csi-cfg/driver.yaml
      volumeMounts:
     ...
      - mountPath: /tmp/csi-cfg
        name: hostpath-config-volume
...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hostpath-config
  namespace: sonobuoy
data:
  driver.yaml: |
    ...
```
