### ISSUE TITLE
Umbrella issue for certified-conformance bug 1388

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1389]
**What steps did you take and what happened:**
See https://github.com/vmware-tanzu/sonobuoy/issues/1388

TODO:
 - [x] Check which releases this applies to
 - [x] Patch master
 - [x] Release new point release
 - [x] Mark impacted versions as invalid for certified-conformance in our README and the upstream instructions

**Comment by johnSchnake** [comment]
Introduced in v0.53; in v0.52 I got this:

```
~/Downloads/sonobuoy_0.52.0_darwin_amd64/sonobuoy gen --mode=certified-conformance --kubernetes-version=ignore | rg FOCUS --context=5
      result-format: junit
    spec:
      command:
      - /run_e2e.sh
      env:
      - name: E2E_FOCUS
        value: \[Conformance\]
      - name: E2E_PARALLEL
        value: "false"
      - name: E2E_SKIP
      - name: E2E_USE_GO_RUNNER
      ```

So you can see that the skip value is empty. Impacted versions are therefore v0.53.0 and v0.53.1
