### ISSUE TITLE
Windows IP bug?

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1443]
Trying to use the windows-dev-tools to setup a local windows cluster but the pod tries to query the API server and gets:

```
time="2021-09-30T12:57:02-07:00" level=error msg="could not get api group resources: Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
```
When I just exec into the container, the curl command also fails. I thought this was due to the networking being wrong but I checked where it was getting the IP from and saw:
```
$ kubectl cluster-info
Kubernetes control plane is running at https://10.20.30.10:6443
```

And when I tried to curl to that IP/port from the container things worked fine.

So are we grabbing the wrong IP? Investigation needed.

**Comment by johnSchnake** [comment]
Sonobuoy is using what client-go is gives it which is using the in-cluster config based on the env vars: `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`.

So why is Sonobuoy unable to curl the api at that?

**Comment by jayunit100** [comment]
hmhmmmmmmm interesting ... 
- 10.96.0.1 is the INTERNAL service IP of the apiserver, so
-  sonobuoy CANT connect to the k8s APIServer over the internal endpoint ,
-  i WONDER if , in GENERAL we have a bug in the dev-tools around the internal service endpoint not working?

That SPECIFIC service is forwarded through kube proxy on the linux node.  

So i guess the question would be

```
is kube proxy running on the linux ontrol plane when sonobuoy starts up ?
```

**Comment by johnSchnake** [comment]
kube-proxy is running and working but only from containers on the linux node.

I launched this pod:
```
apiVersion: v1
kind: Pod
metadata:
  name: pause
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - name: pause
    image: ubuntu
    command: [ "sh", "-c", "echo 'Sleeping; exec here to run stuff' && sleep 99999" ]
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - key: kubernetes.io/e2e-evict-taint-key
    operator: Exists
```
Another would be a better choice; I had to do all the apt-get update/install sudo/ install curl etc

But then
```
kubectl exec pause -- curl -k https://10.96.0.1:443/api
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/api\"",
  "reason": "Forbidden",
  "details": {

  },
  "code": 403
```

I know the 403 isn't an issue; I'm not actually setting the right headers and such. But the 403 is indicative that the API server was responding there.

When I do the same from the sonobuoy pod it just times out since it can't resolve that IP/port

**Comment by johnSchnake** [comment]
kube-proxy description here:
```
$ kubectl describe pod kube-proxy-mcgml -n kube-system
Name:                 kube-proxy-mcgml
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 controlplane/10.20.30.10
Start Time:           Thu, 30 Sep 2021 13:00:03 -0500
Labels:               controller-revision-hash=5668795b7d
                      k8s-app=kube-proxy
                      pod-template-generation=1
Annotations:          <none>
Status:               Running
IP:                   10.20.30.10
IPs:
  IP:           10.20.30.10
Controlled By:  DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Container ID:  docker://78957c2019e1ffa704c9f6119c5c09427699d7f92825db943a45ce22974a8dfe
    Image:         gcr.io/k8s-staging-ci-images/kube-proxy:v1.22.0-alpha.3.31_a3abd06ad53b2f
    Image ID:      docker-pullable://gcr.io/k8s-staging-ci-images/kube-proxy@sha256:bdc77e13fe8243193cf83ed3e24531e04894165128a37d03abec2d3cccb7136a
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    State:          Running
      Started:      Thu, 30 Sep 2021 13:00:03 -0500
    Ready:          True
    Restart Count:  0
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7dt7l (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:
  kube-api-access-7dt7l:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason            Age                  From     Message
  ----     ------            ----                 ----     -------
  Warning  DNSConfigForming  15m (x189 over 20h)  kubelet  Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 4.2.2.1 4.2.2.2 208.67.220.220
```

and the proxy config settings:
```
kubectl exec kube-proxy-mcgml -n kube-system -- cat /var/lib/kube-proxy/config.conf
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
bindAddressHardFail: false
clientConnection:
  acceptContentTypes: ""
  burst: 0
  contentType: ""
  kubeconfig: /var/lib/kube-proxy/kubeconfig.conf
  qps: 0
clusterCIDR: 100.244.0.0/16
configSyncPeriod: 0s
conntrack:
  maxPerCore: null
  min: null
  tcpCloseWaitTimeout: null
  tcpEstablishedTimeout: null
detectLocalMode: ""
enableProfiling: false
healthzBindAddress: ""
hostnameOverride: ""
iptables:
  masqueradeAll: false
  masqueradeBit: null
  minSyncPeriod: 0s
  syncPeriod: 0s
ipvs:
  excludeCIDRs: null
  minSyncPeriod: 0s
  scheduler: ""
  strictARP: false
  syncPeriod: 0s
  tcpFinTimeout: 0s
  tcpTimeout: 0s
  udpTimeout: 0s
kind: KubeProxyConfiguration
metricsBindAddress: ""
mode: ""
nodePortAddresses: null
oomScoreAdj: null
portRange: ""
showHiddenMetricsForVersion: ""
udpIdleTimeout: 0s
winkernel:
  enableDSR: false
  networkName: ""
  sourceVip: ""%
```
