### ISSUE TITLE
Sonobuoy running multiple plugins failing with nil pointer exception

### ISSUE THREAD

**Issue by rapatchi** [vmware-tanzu/sonobuoy#1528]
**What steps did you take and what happened:**
sonobuoy run --plugin <plugin-yaml-path1> --plugin <plugin-yaml-path2> is failing with the below error:
PS D:\azure-arc-kubernetes-conformance\src\plugins> sonobuoy run --plugin .\core\conformance.yaml --plugin 
.\arc_agent_cleanup\arc_agent_cleanup.yaml

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x179b1a2]

goroutine 1 [running]:
github.com/vmware-tanzu/sonobuoy/pkg/client.autoAttachResultsDir(0xc00028df10, 0x2, 0x2, 0x1bd7275, 0x15)
        /home/runner/work/sonobuoy/sonobuoy/pkg/client/gen.go:295 +0x62
github.com/vmware-tanzu/sonobuoy/pkg/client.(*SonobuoyClient).GenerateManifestAndPlugins(0xc000399830, 0xc00030a180, 0x3, 0x28a1550, 0xc000778160, 0xc00080fd30, 0x5fe8ff, 0x38, 0x2839c70, 0x1bc8a01)
        /home/runner/work/sonobuoy/sonobuoy/pkg/client/gen.go:204 +0xcb7
github.com/vmware-tanzu/sonobuoy/pkg/client.(*SonobuoyClient).GenerateManifest(...)
        /home/runner/work/sonobuoy/sonobuoy/pkg/client/gen.go:89
github.com/vmware-tanzu/sonobuoy/pkg/client.(*SonobuoyClient).Run(0xc000399830, 0xc00030a180, 0x28a1550, 0x0)
        /home/runner/work/sonobuoy/sonobuoy/pkg/client/run.go:212 +0x11e
github.com/vmware-tanzu/sonobuoy/cmd/sonobuoy/app.submitSonobuoyRun.func1(0xc00012f400, 0xc000093480, 0x0, 0x4)
        /home/runner/work/sonobuoy/sonobuoy/cmd/sonobuoy/app/run.go:100 +0x24a
github.com/spf13/cobra.(*Command).execute(0xc00012f400, 0xc000093400, 0x4, 0x4, 0xc00012f400, 0xc000093400)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dac80, 0x0, 0x1906640, 0xc00007e058)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/runner/work/sonobuoy/sonobuoy/main.go:27 +0x2e 

**What did you expect to happen:**
Successfully able to run both plugins

**Anything else you would like to add:**

**Environment:**
- Sonobuoy version: v0.55.0 
- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", GitCommit:"ed93e7ea8f833824d05578765c2ad3efbebbfebe", GitTreeState:"clean", BuildDate:"2021-10-21T03:31:08Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure 
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

**Comment by johnSchnake** [comment]
Could you provide the yaml files for those plugins? My first repro was just to confirm that the default plugins worked liked this `--plugin e2e --plugin systemd-logs` and those were fine, then I added a few other plugins I had around and those worked fine as well.

Clearly there is something to fix here, but seeing your plugin that triggered this will help me follow the logic and potentially forsee other issues that may be related.

**Comment by rapatchi** [comment]
**conformance.yaml**:

```
podSpec:
  containers:
    - name: clusterconnecttest
      image: arck8sconformance.azurecr.io/arck8sconformance/clusterconnect:0.1.5
      imagePullPolicy: Always
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
sonobuoy-config:
  driver: Job
  plugin-name: azure-arc-platform
  result-format: junit
spec:
  image: rapatchi/arc-core:v0.1.4
  imagePullPolicy: Always
  name: plugin
  resources: {}
  volumes:
  - name: results
    emptyDir: {}
```
    
   **cleanup.yaml**
```
podSpec:
  containers:
    - name: clusterconnecttest
      image: arck8sconformance.azurecr.io/arck8sconformance/clusterconnect:0.1.5
      imagePullPolicy: Always
  restartPolicy: Never
  serviceAccountName: sonobuoy-serviceaccount
sonobuoy-config:
  driver: Job
  plugin-name: azure-arc-platform
  result-format: junit
spec:
  image: rapatchi/arc-core:v0.1.4
  imagePullPolicy: Always
  name: plugin
  resources: {}
  volumes:
  - name: results
    emptyDir: {}
```
