### ISSUE TITLE
Plugins dont need empty resources or volume mount

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1649]
When creating a plugin via `sonobuoy gen plugin` or even looking at the default e2e/systemd-logs plugins they still show

```
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results
```

Although the volume mount is correct here (the default value) sonobuoy later makes sure that all the plugins agree and that its what the sonobuoy worker sidecar is expecting. So the value here doesn't really matter; what the sidecar expects is what matters.

It would make things less verbose/confusing if we just removed those sections.
