### ISSUE TITLE
Customizing Plug-in PodSpecs not applying imagePullPolicy

### ISSUE THREAD

**Issue by nneram** [vmware-tanzu/sonobuoy#1652]
Customizing Plug-in PodSpecs not applying imagePullPolicy

**What steps did you take and what happened:**

Using this pod spec `e2e.yaml`: 
```
podSpec:
  containers: []
  imagePullPolicy: Always
  restartPolicy: Never
  imagePullSecrets:
  - name: regcred
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - key: kubernetes.io/e2e-evict-taint-key
    operator: Exists
sonobuoy-config:
  driver: Job
  plugin-name: e2e
  result-format: manual
  result-files:
    - e2e-results.yaml
spec:
  args:
  - ./run-e2e.sh
  command:
  - ./run.sh
  image: some/private/registry/e2e:latest
  imagePullPolicy: Always
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results
```
And this command : 

```
sonobuoy run  --namespace e2e --plugin //tmp/e2e-d25o/e2e.yaml  --plugin-env e2e.E2E_FOCUS="test" --skip-preflight --wait
```

`sonobuoy-e2e-job-f072ea79e49c443a` pod running with `imagePullPolicy: IfNotPresent`

**What did you expect to happen:**

`sonobuoy-e2e-job-f072ea79e49c443a` pod running with `imagePullPolicy: Always`
    

**Anything else you would like to add:**

The expected behavior is working on the release https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.50.0
Not working on v0.55.0 and v0.56.3

**Environment:**

- Sonobuoy version:
```
Sonobuoy Version: v0.56.3
MinimumKubeVersion: 1.17.0
MaximumKubeVersion: 1.99.99
GitSHA: 1005bee8fff1b8daa30ddbcca717d03384630a71
GoVersion: go1.16.14
Platform: linux/386
API Version check skipped due to missing `--kubeconfig` or other error
 ```
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```
