### ISSUE TITLE
Gen Plugin includes unnecessary info

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#1691]
**Describe the solution you'd like**
The results volumeMount gets added on the server and the user doesn't have to worry about it at all. It is explicitly ignored if it conflicts with what the aggregator was configured to use.

In addition, no need to print an empty `resources` value.

i.e. Remove these lines from `gen plugin [e2e|systemd-logs]`
```
  resources: {}
  volumeMounts:
  - mountPath: /tmp/sonobuoy/results
    name: results
```
