### ISSUE TITLE
sonobuoy quick mode seems to be broken in v0.56.6

### ISSUE THREAD

**Issue by Payback159** [vmware-tanzu/sonobuoy#1715]
**What steps did you take and what happened:**
I am using sonobuoy in my kubernetes pipeline. Today I updated sonobuoy from v0.56.0 to v0.56.6 and executed.

`sonobuoy run --wait --mode quick --kubeconfig "$KUBECONFIG" --level panic`

The sonobuoy pod is created in the sonobuoy namespace and the pod enters the running state but the run does not finish.
no log outputs with `kubectl logs -n sonobuoy sonobuoy`

Client-Side:

```bash
15:37:41 Waiting for the aggregator status to become Running. Currently the status is Status: Running
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
./tests/sonobuoy/sonobuoy.sh: line 26:    14 Terminated              sonobuoy run --wait --mode quick --kubeconfig "$KUBECONFIG" --level panic
sonobuoy.tar.gz
```

**What did you expect to happen:**

quick mode check executes and my script is running the next steps.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.56.6
- Kubernetes version: (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

```bash
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Sonobuoy tarball (which contains * below)

**Comment by Payback159** [comment]
I am also running 

`sonobuoy run --wait --kubeconfig "$KUBECONFIG" --mode=non-disruptive-conformance --sonobuoy-image "$PRIVATE_REG"/sonobuoy/sonobuoy:"$SONOBUOY_VERSION" --systemd-logs-image "$PRIVATE_REG"/sonobuoy/systemd-logs:v0.3 --kube-conformance-image "$PRIVATE_REG"/conformance:"$CLUSTER_VERSION" --e2e-repo-config "$E2E_REPO_CONFIG"`

and

`sonobuoy run --wait --kubeconfig "$KUBECONFIG" --mode=certified-conformance --sonobuoy-image "$PRIVATE_REG"/sonobuoy/sonobuoy:"$SONOBUOY_VERSION" --systemd-logs-image "$PRIVATE_REG"/sonobuoy/systemd-logs:v0.3 --kube-conformance-image "$PRIVATE_REG"/conformance:"$CLUSTER_VERSION" --e2e-repo-config "$E2E_REPO_CONFIG"`

At the moment it looks like these are running as usual.

**Comment by johnSchnake** [comment]
Can you give me the output of:
```
sonobuoy gen --wait --mode quick --kubeconfig "$KUBECONFIG" --level panic
```

I just confirmed that I can run quick mode with 56.6 and our CI runs the quick mode as well. Its not obvious what the issue would be if you can run other checks with it.

We obviously take it seriously when a problem can occur with the simplest of the commands though.

**Comment by Payback159** [comment]
Hello @johnSchnake,

thank you for your quick response. The pipeline is running right now with conformance tests enabled. I will send you the output of the mentioned commands tomorrow at the latest. Regarding the Pulled Image, I can't imagine it 100% because the sonobuoy container goes into running status. So from the point of view of kubernetes everything seems to be fine.

For my pipeline it is not so tragic, because I use the quick mode only for a preflight-check in my logic... just thought, should it really be a bug in v0.56.6, then it could hit others too and that would not be nice :)

**Comment by johnSchnake** [comment]
> from the point of view of kubernetes everything seems to be fine.

I'm not positive thats the case; the output from the logs say its in the RUNNING state but there could be nuance to that potentially. 

The fact that it never got to the next step of launching plugins and monitoring them means that it stalled out or was unable to update its status. Regardless, quick mode only changes the plugin values and nothing with the aggregator so the fact that the aggregator didnt give any more output points to some other general issue unrelated to e2e/quick mode.

If you can give me the output of `gen` as discussed above, but if you can repro the issue the most important thing would be the output of `sonobuoy logs` which will show me what the aggregator is doing. Using the `--wait` flag effectively keeps polling `sonobuoy status` but doesnt show all the logs.

**Comment by Payback159** [comment]
> Can you give me the output of:
> 
> ```
> sonobuoy gen --wait --mode quick --kubeconfig "$KUBECONFIG" --level panic
> ```
> 
> I just confirmed that I can run quick mode with 56.6 and our CI runs the quick mode as well. Its not obvious what the issue would be if you can run other checks with it.
> 
> We obviously take it seriously when a problem can occur with the simplest of the commands though.

Command
```bash
sonobuoy gen --wait --mode quick --kubeconfig "$KUBECONFIG" --level panic
```

Output
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: sonobuoy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-serviceaccount
  namespace: sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    component: sonobuoy
    namespace: sonobuoy
  name: sonobuoy-serviceaccount-sonobuoy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sonobuoy-serviceaccount-sonobuoy
subjects:
- kind: ServiceAccount
  name: sonobuoy-serviceaccount
  namespace: sonobuoy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    component: sonobuoy
    namespace: sonobuoy
  name: sonobuoy-serviceaccount-sonobuoy
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - /metrics
  - /logs
  - /logs/*
  verbs:
  - get
---
apiVersion: v1
data:
  config.json: '{"Description":"DEFAULT","UUID":"","Version":"v0.56.6","ResultsDir":"/tmp/sonobuoy/results","Resources":null,"Filters":{"Namespaces":".*","LabelSelector":""},"Limits":{"PodLogs":{"Namespaces":"kube-system","SonobuoyNamespace":true,"FieldSelectors":[],"LabelSelector":"","Previous":false,"SinceSeconds":null,"SinceTime":null,"Timestamps":false,"TailLines":null,"LimitBytes":null}},"QPS":30,"Burst":50,"Server":{"bindaddress":"0.0.0.0","bindport":8080,"advertiseaddress":"","timeoutseconds":21600},"Plugins":null,"PluginSearchPath":["./plugins.d","/etc/sonobuoy/plugins.d","~/sonobuoy/plugins.d"],"Namespace":"sonobuoy","WorkerImage":"sonobuoy/sonobuoy:v0.56.6","ImagePullPolicy":"IfNotPresent","ImagePullSecrets":"","AggregatorPermissions":"clusterAdmin","ProgressUpdatesPort":"8099","SecurityContextMode":"nonroot"}'
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-config-cm
  namespace: sonobuoy
---
apiVersion: v1
data:
  plugin-0.yaml: |-
    podSpec:
      containers: []
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Never
      serviceAccountName: sonobuoy-serviceaccount
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - key: kubernetes.io/e2e-evict-taint-key
        operator: Exists
    sonobuoy-config:
      driver: Job
      plugin-name: e2e
      result-format: junit
    spec:
      command:
      - /run_e2e.sh
      env:
      - name: E2E_EXTRA_ARGS
        value: --progress-report-url=http://localhost:8099/progress
      - name: E2E_FOCUS
        value: Pods should be submitted and removed
      - name: E2E_PARALLEL
        value: "false"
      - name: E2E_USE_GO_RUNNER
        value: "true"
      - name: RESULTS_DIR
        value: /tmp/sonobuoy/results
      - name: SONOBUOY
        value: "true"
      - name: SONOBUOY_CONFIG_DIR
        value: /tmp/sonobuoy/config
      - name: SONOBUOY_K8S_VERSION
        value: v1.18.17
      - name: SONOBUOY_PROGRESS_PORT
        value: "8099"
      - name: SONOBUOY_RESULTS_DIR
        value: /tmp/sonobuoy/results
      image: k8s.gcr.io/conformance:v1.18.17
      imagePullPolicy: IfNotPresent
      name: e2e
      volumeMounts:
      - mountPath: /tmp/sonobuoy/results
        name: results
  plugin-1.yaml: |-
    podSpec:
      containers: []
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: sonobuoy-serviceaccount
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /
        name: root
    sonobuoy-config:
      driver: DaemonSet
      plugin-name: systemd-logs
      result-format: raw
    spec:
      command:
      - /bin/sh
      - -c
      - /get_systemd_logs.sh; while true; do echo "Plugin is complete. Sleeping indefinitely
        to avoid container exit and automatic restarts from Kubernetes"; sleep 3600; done
      env:
      - name: CHROOT_DIR
        value: /node
      - name: NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: RESULTS_DIR
        value: /tmp/sonobuoy/results
      - name: SONOBUOY
        value: "true"
      - name: SONOBUOY_CONFIG_DIR
        value: /tmp/sonobuoy/config
      - name: SONOBUOY_K8S_VERSION
        value: v1.18.17
      - name: SONOBUOY_PROGRESS_PORT
        value: "8099"
      - name: SONOBUOY_RESULTS_DIR
        value: /tmp/sonobuoy/results
      image: sonobuoy/systemd-logs:v0.4
      imagePullPolicy: IfNotPresent
      name: systemd-logs
      securityContext:
        privileged: true
      volumeMounts:
      - mountPath: /node
        name: root
      - mountPath: /tmp/sonobuoy/results
        name: results
kind: ConfigMap
metadata:
  labels:
    component: sonobuoy
  name: sonobuoy-plugins-cm
  namespace: sonobuoy
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    component: sonobuoy
    sonobuoy-component: aggregator
    tier: analysis
  name: sonobuoy
  namespace: sonobuoy
spec:
  containers:
  - args:
    - aggregator
    - --no-exit
    - --level=panic
    - -v=0
    - --alsologtostderr
    command:
    - /sonobuoy
    env:
    - name: SONOBUOY_ADVERTISE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    image: sonobuoy/sonobuoy:v0.56.6
    imagePullPolicy: IfNotPresent
    name: kube-sonobuoy
    volumeMounts:
    - mountPath: /etc/sonobuoy
      name: sonobuoy-config-volume
    - mountPath: /plugins.d
      name: sonobuoy-plugins-volume
    - mountPath: /tmp/sonobuoy
      name: output-volume
  restartPolicy: Never
  securityContext:
    fsGroup: 2000
    runAsGroup: 3000
    runAsUser: 1000
  serviceAccountName: sonobuoy-serviceaccount
  tolerations:
  - key: kubernetes.io/e2e-evict-taint-key
    operator: Exists
  volumes:
  - configMap:
      name: sonobuoy-config-cm
    name: sonobuoy-config-volume
  - configMap:
      name: sonobuoy-plugins-cm
    name: sonobuoy-plugins-volume
  - emptyDir: {}
    name: output-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: sonobuoy
    sonobuoy-component: aggregator
  name: sonobuoy-aggregator
  namespace: sonobuoy
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    sonobuoy-component: aggregator
  type: ClusterIP
---

```
