### ISSUE TITLE
Rolling up junit results on daemonset plugin incorrect

### ISSUE THREAD

**Issue by johnSchnake** [vmware-tanzu/sonobuoy#900]
**What steps did you take and what happened:**
I had a plugin that ran a junit producing plugin on a 2 node cluster as a daemonset.

One of the nodes, which had test failures, did not get a status at all:

```
- name: kind-worker
  status: ""
  items:
  - name: output.xml
    status: failed
    meta:
      file: results/kind-worker/tmp/results/output.xml
    items:
    - name: benchmark
      status: failed
      items:
      - name: benchmark-1.7.1
        status: skipped
```

The other node in the cluster did get a properly bubbled-up `failed` status.

**What did you expect to happen:**
Each nodes results should be aggregated appropriately.

**Anything else you would like to add:**
At this time I don't want to share the plugin I was using as it is a WIP but I think the bug should be fairly easy to repro/identify in the code.
